### PR TITLE
Fix #274 - replace HYDRA_PROFILING with PROFILING

### LINKED ISSUE #274: cmd: hydra help host profiling typo
`HYDRA_PROFILING` should be `PROFILING`:

```
DEBUG CONTROLS
==============

- HYDRA_PROFILING: Set "HYDRA_PROFILING=cpu" to enable cpu profiling and "HYDRA_PROFILING=memory" to enable memory profiling.
        It is not possible to do both at the same time.
        Example: HYDRA_PROFILING=cpu

```

### PR DESCRIPTION
**Pull request by otremblay**
As advertised in title.

### CODE REVIEW

**Comment by arekkas** [comment]
awesome! could you please sign off your commit using `git commit --amend -s`? :)

**Comment by otremblay** [comment]
There ya go :)

**Comment by otremblay** [comment]
Lol just realized that I'm ahead of time for hacktoberfest. XD Oh well. Getting warmed up I guess.

**Comment by arekkas** [comment]
@otremblay there's nothing better than getting warmed up :D thanks for the contribution!

**Pull request merged**
