### PR TITLE
client: fix client.GetClients() for multiple clients

### PR DESCRIPTION
**Pull request by boyvinall**
fix for #150

Signed-off-by: Matt Vinall <boyvinall@gmail.com>

### CODE REVIEW

**Comment by arekkas** [comment]
Could you please add a test case as discussed in gitter? It would be awesome to automate the check :)

**Comment by arekkas** [comment]
nvm, I'll create one myself. Thanks for this!

**Comment by boyvinall** [comment]
sorry, just catching up again, thanks. If I get time then I'll add one in a bit..

**Comment by arekkas** [comment]
already on it

**Comment by arekkas** [comment]
see #152

**Pull request merged**
