### PR TITLE
client: add GetName() accessor method

### PR DESCRIPTION
**Pull request by boyvinall**
Fairly simple addition.  Would like to add this to fosite in a sec too.

Signed-off-by: Matt Vinall <boyvinall@gmail.com>

### CODE REVIEW

**Comment by arekkas** [comment]
What's the benefit of having a method for this? `GetHashedSecret`, `GetGrantedScopes`, ... are being used to satisfy [`fosite.Client`](https://github.com/ory-am/fosite/blob/master/client.go#L12)

**Comment by arekkas** [comment]
Ah wow, I overread the "Would like to add this to fosite in a sec too." part - haha :D

**Comment by boyvinall** [comment]
https://github.com/ory-am/hydra/blob/master/client/manager_http.go#L17 returns a fosite.Client interface, so I can't read the name :)

**Comment by arekkas** [comment]
Still, there's no reason to bloat the `fosite.Client` interface - it should only have methods that are useful to the fosite library.

**Comment by arekkas** [comment]
Ah I see

**Comment by arekkas** [comment]
Why not simply do `hm.GetClient('123').(*client.Client)`?

**Comment by boyvinall** [comment]
Ah yeah, sorry

**Comment by skymeyer** [comment]
@arekkas wouldn't it be more consistent to return ```Client``` instead of ```fosite.Client``` to line up with with ```GetClients``` ? Just a detail though.

```go
func (m *HTTPManager) GetClient(id string) (*Client, error) {
```

**Comment by arekkas** [comment]
No, because `GetClient(id string) (*Client, error)` does not implement `fosite.Storage` :)

**Comment by arekkas** [comment]
However, I see how this is an issue for the HTTPManager

**Pull request closed without merging**
