### PR TITLE
Update jwt-go and resolve warden regression issue

### PR DESCRIPTION
**Pull request by arekkas**

### CODE REVIEW

**Comment by arekkas** [comment]
This PR should not break the database. Although the Signature of JWT Containers changed, they are not being saved to the database in Hydra. Plus, the float64 change won't matter to json anyways.

@leetal let me know if you disagree

**Comment by leetal** [comment]
Seems good to me! 
Will have to fix a new version of fosite as well. Time for a 0.2.5? :)

**Comment by arekkas** [comment]
I released fosite as 0.3.0 because it's still a possible bc break. :)

**Comment by leetal** [comment]
Ah, okey! :+1:

**Pull request merged**
